version: '3'

services:
  postgres:
    image: postgres:15.3
    ports:
      - '5432:5432'
    networks:
      - common-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - ketotrain_postgres-data:/data/postgres

  redis-server:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
    networks:
      - common-network

networks:
  common-network:
    external: true

volumes:
  ketotrain_postgres-data:
    driver: local
