export enum ActionType {
  UPDATE_HAS_SEEN_INTRO_VALUE = 'UPDATE_HAS_SEEN_INTRO_VALUE',
  UPDATE_SEARCH_FOOD_LIST = 'UPDATE_SEARCH_FOOD_LIST',
  INIT_SEARCH_FOOD_LIST = 'INIT_SEARCH_FOOD_LIST',
  UPDATE_FAV_FOOD_LIST = 'UPDATE_FAV_FOOD_LIST',
  INIT_FAV_FOOD_LIST = 'INIT_FAV_FOOD_LIST',
}
