require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_frameworks! :linkage => :static    # firebase auth
$RNFirebaseAsStaticFramework = true    # firebase auth

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

$RNFirebaseAnalyticsWithoutAdIdSupport=true   #firebase auth

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNScreens')
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end

pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true

target 'KetoLimit' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
      :path => config[:reactNativePath],
      # to enable hermes on iOS, change `false` to `true` and then install pods
      :production => production,
      :hermes_enabled => flags[:hermes_enabled],
      :fabric_enabled => flags[:fabric_enabled],
      #:flipper_configuration => FlipperConfiguration.enabled,  # Comment this out to disable Flipper
      # An absolute path to your application root.
      :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  target 'KetoLimitTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '5.0'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
        end
    end
  end
end
